########################################################################################
# Base image stub for pyNLDI-Crawler
# Dockerfiles from code.usgs.gov/wma/pygeoapi and Clifford Hill

FROM artifactory.wma.chs.usgs.gov/docker-official-mirror/ubuntu:focal as root-cert
#FROM ubuntu:22.04 as root-cert

USER root

LABEL maintainer1="Erik Wojtylko <ewojtylko@usgs.gov>"
LABEL maintainer2=""

# -yq simplified with -q=2 which implies y
# software-properties-common
RUN apt-get update && apt-get install -y apt-transport-https
RUN apt-get install -q=2 --no-install-recommends software-properties-common

# Needs DOI Cert to work.  VPN is needed for artifactory image and cert is needed to pip install through vpn.
COPY ./docker/DOIRootCA2.cer /usr/local/share/ca-certificates/DOIRootCA2.crt
RUN chmod 644 /usr/local/share/ca-certificates/DOIRootCA2.crt
RUN update-ca-certificates

ENV PIP_CERT="/etc/ssl/certs/ca-certificates.crt" \
    SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt" \
    CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt" \
    REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"

########################################################################################
# Set up Ubuntu Linux Environment now that certs are in order
FROM root-cert as ubuntu-base

RUN apt-get update 
RUN apt-get install -q=2 --fix-missing --no-install-recommends \
curl \
python3-pip \
python3-venv \
python3.10

#RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
RUN mkdir -p /nldi-crawler-py
WORKDIR /nldi-crawler-py
RUN pip install -U pip setuptools
RUN pip install poetry
COPY . .
RUN poetry install
# The rest...  also need to clean up chaff